{% set name = "pypresseportal" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypresseportal-{{ version }}.tar.gz
  sha256: bd5088daacdcbd4af4f6358d42c822a293c43f44fb58507cea3cda4bec5ba069

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - requests
    - setuptools
  run:
    - python >={{ python_min }}
    - requests

test:
  imports:
    - pypresseportal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tcmetzger/pypresseportal
  summary: Python wrapper for the presseportal.de API
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
